[package]
name = "kefir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.2"
log = "0.4.20"
num-derive = "0.4.2"
num-traits = "0.2.18"
